### ISSUE TITLE
Bug button load more

### ISSUE THREAD

**Issue by prhost** [SunLabDev/oc-unsplashpicker-plugin#2]
Hello, initially congratulations for the plugin, it's helping me a lot.

I would like to report a basic problem, when you click on load more, and search for another term, it does not populate the result. Only that.

Thanks.

**Comment by RomainMazB** [comment]
Hi, sorry for the elapsed time!
I confirmed the issue when we search for another term, I will investigate on this soon.

I guess the proper way is to cleanup all the previous results and do a new clean search showing the new terms results.

**Comment by RomainMazB** [comment]
Fixed in 1.0.5 by #4.
Again @prhost,  thanks to report the issue :)
